/**
 * Builds projects-data.js from the markdown files in projects/.
 * Run with: npm run build
 */

const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');
const { marked } = require('marked');

const PROJECTS_DIR = path.join(__dirname, '..', 'projects');
const OUTPUT_FILE = path.join(__dirname, '..', 'projects-data.js');

marked.setOptions({ gfm: true });

/**
 * Pulls a trailing "## ... Affiliations" section (a bullet list of
 * "**Name** — Affiliation" lines) out of the markdown body, so it can be
 * shown as part of the Team Members line at the top of the page instead of
 * as a separate section at the bottom. Returns the body with that section
 * removed, plus the parsed { name, affiliation } list (empty if none found).
 */
function extractAffiliations(content) {
  const headingMatch = /^##\s*.*Affiliations.*$/im.exec(content);
  if (!headingMatch) {
    return { content, authors: [] };
  }

  const afterHeading = content.slice(headingMatch.index + headingMatch[0].length);
  const nextHeadingMatch = /^#{2,3}\s+/m.exec(afterHeading);
  const sectionEnd = nextHeadingMatch ? nextHeadingMatch.index : afterHeading.length;
  const sectionBody = afterHeading.slice(0, sectionEnd);

  const authors = [];
  const lineRegex = /^[*-]\s+\*\*(.+?)\*\*\s+—\s+(.+?)\s*$/gm;
  let lineMatch;
  while ((lineMatch = lineRegex.exec(sectionBody)) !== null) {
    authors.push({ name: lineMatch[1].trim(), affiliation: lineMatch[2].trim() });
  }

  const cleanedContent = content.slice(0, headingMatch.index) + afterHeading.slice(sectionEnd);
  return { content: cleanedContent.trim(), authors };
}

function loadProjects() {
  if (!fs.existsSync(PROJECTS_DIR)) {
    throw new Error(`Missing projects/ directory at ${PROJECTS_DIR}`);
  }

  // Filenames like "2025-NCT.md" sort naturally by year, then team.
  const files = fs.readdirSync(PROJECTS_DIR)
    .filter(f => f.endsWith('.md'))
    .sort();

  const projects = files.map((filename, index) => {
    const raw = fs.readFileSync(path.join(PROJECTS_DIR, filename), 'utf8');
    const { data, content } = matter(raw);

    for (const required of ['year', 'team', 'title']) {
      if (!data[required]) {
        throw new Error(`${filename}: missing required frontmatter field "${required}"`);
      }
    }

    const { content: bodyContent, authors } = extractAffiliations(content);

    return {
      id: index + 1,
      year: String(data.year),
      team: data.team,
      members: data.members || '',
      authors,
      title: data.title,
      desc: data.desc || '',
      keywords: data.keywords || [],
      thumb: data.thumb || '',
      youtubeEmbed: data.youtubeEmbed || null,
      videoUrl: data.videoUrl || null,
      gallery: data.gallery || [],
      blogContent: marked.parse(bodyContent),
      materials: data.materials || []
    };
  });

  // Display order: most recent year first. Array.prototype.sort is stable,
  // so teams within the same year keep their filename order.
  projects.sort((a, b) => Number(b.year) - Number(a.year));

  return projects;
}

function serializeProjects(projects) {
  return `/**
 * Projects Data - AUTO-GENERATED by tools/build.js — do not edit by hand.
 * Edit the markdown files in projects/ instead, then run: npm run build
 */

const rawProjects = ${JSON.stringify(projects, null, 2)};

const fallbackImage = "data:image/svg+xml;charset=UTF-8,%3Csvg width='600' height='400' xmlns='http://www.w3.org/2000/svg'%3E%3Crect width='100%25' height='100%25' fill='%23e2e8f0'/%3E%3Ctext x='50%25' y='50%25' dominant-baseline='middle' text-anchor='middle' font-family='sans-serif' font-size='20px' fill='%2364748b'%3EImage Not Found%3C/text%3E%3C/svg%3E";
`;
}

const projects = loadProjects();
fs.writeFileSync(OUTPUT_FILE, serializeProjects(projects));
console.log(`Built ${projects.length} project(s) -> ${path.relative(process.cwd(), OUTPUT_FILE)}`);
